development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: api_production

